#!/usr/bin/env python3
"""Generate migrations/seed_problems.sql from task definitions and notebooks.

Reads task dicts from torch_judge/tasks/, extracts content from template and
solution notebooks, and writes an idempotent SQL seed file.

Usage:
    python scripts/seed_problems.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

# Ensure project root is on sys.path so torch_judge can be imported.
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from torch_judge.tasks._registry import (
    CATEGORY_ORDER,
    DIFFICULTY_ORDER,
    TASKS,
    list_tasks,
)

TEMPLATES_DIR = PROJECT_ROOT / "templates"
SOLUTIONS_DIR = PROJECT_ROOT / "solutions"
OUTPUT_FILE = PROJECT_ROOT / "migrations" / "seed_problems.sql"

# Map task module names to notebook numbers.
# Notebook filenames follow the pattern: NN_<slug>.ipynb / NN_<slug>_solution.ipynb
# Build a lookup: slug -> notebook number prefix.
_SLUG_TO_TEMPLATE: dict[str, Path] = {}
_SLUG_TO_SOLUTION: dict[str, Path] = {}

for nb in sorted(TEMPLATES_DIR.glob("*.ipynb")):
    # e.g. "01_relu.ipynb" -> slug="relu", or "06_multihead_attention" -> slug="multihead_attention"
    match = re.match(r"(\d+)_(.+)\.ipynb", nb.name)
    if match:
        slug = match.group(2)
        _SLUG_TO_TEMPLATE[slug] = nb

for nb in sorted(SOLUTIONS_DIR.glob("*.ipynb")):
    match = re.match(r"(\d+)_(.+)_solution\.ipynb", nb.name)
    if match:
        slug = match.group(2)
        _SLUG_TO_SOLUTION[slug] = nb

# Map task module names to notebook slugs.
# Task modules: relu, linear, mha, softmax, ...
# Notebook slugs: relu, linear, multihead_attention, softmax, ...
# Most match directly; handle known aliases.
_TASK_TO_NB_SLUG: dict[str, str] = {
    "mha": "multihead_attention",
}


def _read_notebook(path: Path) -> list[dict]:
    """Read notebook cells from an .ipynb file."""
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("cells", [])


def _cell_source(cell: dict) -> str:
    """Get cell source as a single string."""
    src = cell.get("source", [])
    if isinstance(src, list):
        return "".join(src)
    return src


def _extract_template_info(task_id: str) -> dict:
    """Extract description, signature, example, and template_code from a template notebook."""
    nb_slug = _TASK_TO_NB_SLUG.get(task_id, task_id)
    path = _SLUG_TO_TEMPLATE.get(nb_slug)
    if not path:
        return {}

    cells = _read_notebook(path)
    result: dict = {}

    for cell in cells:
        src = _cell_source(cell)
        cell_type = cell.get("cell_type", "code")

        if cell_type == "markdown" and not result.get("description"):
            result["description"] = src.strip()
            # Extract signature from ```python blocks
            sig_match = re.search(r"```python\s*\n((?:def |class ).+)", src)
            if sig_match:
                result["signature"] = sig_match.group(1).strip()
            # Extract example from ### Example section
            ex_match = re.search(r"### Example\s*\n```[^\n]*\n(.*?)```", src, re.DOTALL)
            if ex_match:
                result["example"] = ex_match.group(1).strip()

        if cell_type == "code" and ("YOUR IMPLEMENTATION" in src or "pass  # Replace" in src or "pass  # " in src):
            result["template_code"] = src.strip()

    return result


def _extract_solution_info(task_id: str) -> dict:
    """Extract solution_code and solution_markdown from a solution notebook."""
    nb_slug = _TASK_TO_NB_SLUG.get(task_id, task_id)
    path = _SLUG_TO_SOLUTION.get(nb_slug)
    if not path:
        return {}

    cells = _read_notebook(path)
    result: dict = {}

    for cell in cells:
        src = _cell_source(cell)
        cell_type = cell.get("cell_type", "code")

        if cell_type == "markdown" and not result.get("solution_markdown"):
            result["solution_markdown"] = src.strip()

        if cell_type == "code" and "SOLUTION" in src:
            result["solution_code"] = src.strip()

    return result


def _sql_escape(s: str | None) -> str:
    """Escape a string for PostgreSQL single-quoted literal."""
    if s is None:
        return "NULL"
    # Escape single quotes by doubling them.
    escaped = s.replace("'", "''")
    return f"'{escaped}'"


def _sql_escape_jsonb(obj: object) -> str:
    """Encode an object as a JSONB literal."""
    return _sql_escape(json.dumps(obj, ensure_ascii=False))


def generate_sql() -> str:
    """Generate the full seed SQL."""
    lines: list[str] = [
        "-- Auto-generated by scripts/seed_problems.py",
        "-- Run: python scripts/seed_problems.py",
        "",
    ]

    sorted_tasks = list_tasks()  # sorted by (category_index, difficulty)

    for sort_order, (task_id, task) in enumerate(sorted_tasks, start=1):
        template_info = _extract_template_info(task_id)
        solution_info = _extract_solution_info(task_id)

        slug = task_id
        title = task["title"]
        difficulty = task["difficulty"]
        category = task.get("category", "")
        function_name = task.get("function_name", "")
        hint = task.get("hint", "")
        tests = task.get("tests", [])

        description = template_info.get("description", "")
        signature = template_info.get("signature", "")
        example = template_info.get("example", "")
        template_code = template_info.get("template_code", "")

        solution_code = solution_info.get("solution_code", "")
        solution_markdown = solution_info.get("solution_markdown", "")

        lines.append(f"INSERT INTO problems (slug, title, difficulty, category, function_name, description, signature, example, hint, template_code, tests_json, solution_code, solution_markdown, status, sort_order)")
        lines.append(f"VALUES (")
        lines.append(f"  {_sql_escape(slug)},")
        lines.append(f"  {_sql_escape(title)},")
        lines.append(f"  {_sql_escape(difficulty)},")
        lines.append(f"  {_sql_escape(category)},")
        lines.append(f"  {_sql_escape(function_name)},")
        lines.append(f"  {_sql_escape(description)},")
        lines.append(f"  {_sql_escape(signature)},")
        lines.append(f"  {_sql_escape(example)},")
        lines.append(f"  {_sql_escape(hint)},")
        lines.append(f"  {_sql_escape(template_code)},")
        lines.append(f"  {_sql_escape_jsonb(tests)},")
        lines.append(f"  {_sql_escape(solution_code)},")
        lines.append(f"  {_sql_escape(solution_markdown)},")
        lines.append(f"  'approved',")
        lines.append(f"  {sort_order}")
        lines.append(f")")
        lines.append(f"ON CONFLICT (slug) DO UPDATE SET")
        lines.append(f"  title            = EXCLUDED.title,")
        lines.append(f"  difficulty       = EXCLUDED.difficulty,")
        lines.append(f"  category         = EXCLUDED.category,")
        lines.append(f"  function_name    = EXCLUDED.function_name,")
        lines.append(f"  description      = EXCLUDED.description,")
        lines.append(f"  signature        = EXCLUDED.signature,")
        lines.append(f"  example          = EXCLUDED.example,")
        lines.append(f"  hint             = EXCLUDED.hint,")
        lines.append(f"  template_code    = EXCLUDED.template_code,")
        lines.append(f"  tests_json       = EXCLUDED.tests_json,")
        lines.append(f"  solution_code    = EXCLUDED.solution_code,")
        lines.append(f"  solution_markdown = EXCLUDED.solution_markdown,")
        lines.append(f"  sort_order       = EXCLUDED.sort_order,")
        lines.append(f"  updated_at       = NOW();")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    sql = generate_sql()
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(sql, encoding="utf-8")
    print(f"Wrote {OUTPUT_FILE} ({len(sql)} bytes, {sql.count('INSERT INTO')} problems)")


if __name__ == "__main__":
    main()
